In [64]:
# Classic Imports
import pandas as pd
import re
import copy

In [65]:
# Getting the first Dataset
datasets = pd.read_csv('CSV\semi_clean_one.csv')

In [66]:
# Creating Minute by Minute Dataset
Inc = datasets['INC']

In [67]:
incDataFrame = pd.DataFrame(Inc)

In [68]:
indexList = []
for index in range(0, len(incDataFrame)):
    indexList.append(index)


incDataFrame.insert(1, "ID", indexList, True)

In [69]:
incDataFrame = incDataFrame.dropna()

In [70]:
col_list = list(incDataFrame.columns)
x, y = col_list.index('INC'), col_list.index('ID')
col_list[y], col_list[x] = col_list[x], col_list[y]

incDataFrame = incDataFrame[col_list]

incDataFrame

          ID                                                INC
28        28  .33=Goal_Home.40=Yellow_Away.56=Yellow_Away.60...
29        29  .59=Goal_Away.69=Goal_Home.73=Goal_Away.75=Yel...
30        30  .04=Goal_Away.31=Yellow_Away.42=Yellow_Home.43...
31        31  .56=Yellow_Away.57=Goal_Away.65=Yellow_Away.74...
32        32  .02=Goal_Home.15=Yellow_Away.22=Yellow_Away.22...
...      ...                                                ...
52965  52965  .30=Yellow_Away.31=Yellow_Home.42=Goal_Away.78...
52968  52968  .24=Yellow_Away.43=Yellow_Away.60=Goal_Away.63...
52969  52969  .04=Goal_Away.06=Yellow_Away.17=Yellow_Away.44...
52971  52971  .10=Goal_Home.38=Goal_Home.49=Yellow_Home.66=Y...
52972  52972  .31=Goal_Away.61=Yellow_Away.76=Yellow_Home.84...

[39165 rows x 2 columns]

In [71]:
Goal_Home = []
Goal_Away = []
Yellow_Home = []
Yellow_Away = []
Red_Card_Home = []
Red_Card_Away = []
Own_Home = []
Own_Away = []
drop_list = []
count = 0
drop_id = list(incDataFrame['ID'])

values = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', 
          '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 
          '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', 
          '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', 
          '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', 
          '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90']

attributeValues = ['Goal_Home', 'Goal_Away', 'Yellow_Home', 'Yellow_Away', 'Red_Card_Home', 'Red_Card_Away', 'Own_Home', 'Own_Away']

for inc in incDataFrame['INC']:
    incData = inc
    minute_clean = []
    drop = False
    data = [0, 0, 0, 0, 0, 0, 0, 0]
    first_split = incData.split(".")
    # Second For loop to further split the data
    for second_clean in range(len(first_split)):
        # Another split to create action array by spliting with =
        second_split = first_split[second_clean].split('=')
        # Re appending everything back
        minute_clean.append(second_split)
    for attribute in minute_clean:
        if len(attribute) == 2:
            if attribute[0] not in values:
                drop = True
            if attribute[1] not in attributeValues:
                drop = True
            if attribute[1] in attributeValues:
                if attribute[1] == 'Goal_Home':
                     data[0] = data[0] + 1
                elif attribute[1] == 'Goal_Away':
                    data[1] = data[1] + 1
                elif attribute[1] == 'Yellow_Home':
                    data[2] = data[2] + 1
                elif attribute[1] == 'Yellow_Away':
                    data[3] = data[3] + 1
                elif attribute[1] == 'Red_Card_Home':
                    data[4] = data[4] + 1
                elif attribute[1] == 'Red_Card_Away':
                    data[5] = data[5] + 1
                elif attribute[1] == 'Own_Home':
                    data[6] = data[6] + 1
                elif attribute[1] == 'Own_Away':
                    data[7] = data[7] + 1
    Goal_Home.append(data[0])
    Goal_Away.append(data[1])
    Yellow_Home.append(data[2])
    Yellow_Away.append(data[3])
    Red_Card_Home.append(data[4])
    Red_Card_Away.append(data[5])
    Own_Home.append(data[6])
    Own_Away.append(data[7])
    if drop == True:
            drop_list.append(drop_id[count])
    count = count + 1

In [72]:
incDataFrame.insert(2, "Goal_Home", Goal_Home, True)
incDataFrame.insert(3, "Goal_Away", Goal_Away, True)
incDataFrame.insert(4, "Yellow_Home", Yellow_Home, True)
incDataFrame.insert(5, "Yellow_Away", Yellow_Away, True)
incDataFrame.insert(6, "Red_Card_Home", Red_Card_Home, True)
incDataFrame.insert(7, "Red_Card_Away", Red_Card_Away, True)
incDataFrame.insert(8, "Own_Home", Own_Home, True)
incDataFrame.insert(9, "Own_Away", Own_Away, True)

In [73]:
incDataFrame

,ID,INC,Goal_Home,Goal_Away,Yellow_Home,Yellow_Away,Red_Card_Home,Red_Card_Away,Own_Home,Own_Away
28,28,.33=Goal_Home.40=Yellow_Away.56=Yellow_Away.60...,1,0,4,4,0,0,0,0
29,29,.59=Goal_Away.69=Goal_Home.73=Goal_Away.75=Yel...,2,2,3,1,0,0,0,0
30,30,.04=Goal_Away.31=Yellow_Away.42=Yellow_Home.43...,2,3,2,3,0,0,0,0
31,31,.56=Yellow_Away.57=Goal_Away.65=Yellow_Away.74...,1,1,0,3,0,0,0,0
32,32,.02=Goal_Home.15=Yellow_Away.22=Yellow_Away.22...,1,0,2,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
52965,52965,.30=Yellow_Away.31=Yellow_Home.42=Goal_Away.78...,1,1,1,2,0,0,0,0
52968,52968,.24=Yellow_Away.43=Yellow_Away.60=Goal_Away.63...,0,1,0,3,0,0,0,0
52969,52969,.04=Goal_Away.06=Yellow_Away.17=Yellow_Away.44...,1,1,2,2,0,0,0,0
52971,52971,.10=Goal_Home.38=Goal_Home.49=Yellow_Home.66=Y...,2,0,2,0,0,0,0,0
52972,52972,.31=Goal_Away.61=Yellow_Away.76=Yellow_Home.84...,0,1,2,2,0,0,0,0

In [74]:
minuteDataFrame = incDataFrame[['ID', 'INC']].copy()

In [75]:
test_number = 0
counter = 0
minute_final_list = []
for minutes_number in incDataFrame['INC']:
    minute_temp_list = []
    minute_cleaner = []
    minute_use = minutes_number
    first_spliter = minute_use.split(".")
    for second_cleaner in range(len(first_spliter)):
        second_spliter = first_spliter[second_cleaner].split('=')
        minute_cleaner.append(second_spliter)
    for time in range(0, 91):
        check = False
        for minutes in minute_cleaner:
            if len(minutes) == 2 and minutes[0] in values:
                if int(minutes[0]) == time and check == True:
                    minute_temp_list[time] = minute_temp_list[time] + ',' + minutes[1]
                if int(minutes[0]) == time and check == False:
                    minute_temp_list.append(minutes[1] + '')
                    check = True
        if check == False:
            minute_temp_list.append('-')
    minute_final_list.append(minute_temp_list)
    counter = counter + 1

In [76]:
for insert_count in range(0, 91):
    minute_insert_list = []
    for minute_insert in minute_final_list:
        minute_insert_list.append(minute_insert[insert_count]) 
    minuteDataFrame.insert((insert_count + 2), 'M' + str(insert_count), minute_insert_list, True)

In [77]:
minuteDataFrame

,ID,INC,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
28,28,.33=Goal_Home.40=Yellow_Away.56=Yellow_Away.60...,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Home,-,-
29,29,.59=Goal_Away.69=Goal_Home.73=Goal_Away.75=Yel...,-,-,-,-,-,-,-,-,...,-,-,Yellow_Home,-,-,-,Goal_Home,Yellow_Home,-,-
30,30,.04=Goal_Away.31=Yellow_Away.42=Yellow_Home.43...,-,-,-,-,Goal_Away,-,-,-,...,-,-,-,-,-,-,Yellow_Away,-,-,"Yellow_Away,Yellow_Home"
31,31,.56=Yellow_Away.57=Goal_Away.65=Yellow_Away.74...,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,Yellow_Away
32,32,.02=Goal_Home.15=Yellow_Away.22=Yellow_Away.22...,-,-,Goal_Home,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,"Yellow_Away,Red_Card_Home"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52965,52965,.30=Yellow_Away.31=Yellow_Home.42=Goal_Away.78...,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
52968,52968,.24=Yellow_Away.43=Yellow_Away.60=Goal_Away.63...,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
52969,52969,.04=Goal_Away.06=Yellow_Away.17=Yellow_Away.44...,-,-,-,-,Goal_Away,-,Yellow_Away,-,...,-,-,-,-,-,-,-,-,-,-
52971,52971,.10=Goal_Home.38=Goal_Home.49=Yellow_Home.66=Y...,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
52972,52972,.31=Goal_Away.61=Yellow_Away.76=Yellow_Home.84...,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,Yellow_Away,-,-,-

In [78]:
incDataFrame.drop(['INC'], axis=1, inplace=True)
minuteDataFrame.drop(['INC'], axis=1, inplace=True)

In [79]:
incDataFrame = incDataFrame.drop(drop_list)
minuteDataFrame = minuteDataFrame.drop(drop_list)

In [80]:
incDataFrame.to_csv('RawINCData.csv')
minuteDataFrame.to_csv('MinuteByMinute.csv')