In [24]:
# Classic Imports
import pandas as pd
import re
import copy

In [25]:
# Getting all the Datasets
semiClean = pd.read_csv('CSV\semi_clean_one.csv')
minuteByMinute = pd.read_csv('CSV\MinuteByMinute.csv', dtype='object')
rawInc = pd.read_csv('CSV\RawINCData.csv')

In [26]:
semiClean = semiClean.dropna(subset = ['INC'])

In [35]:
clean_list = semiClean['League'].unique()
count = [0, 0, 0, 0, 0, 0 ,0 ,0]

for balanceCount in semiClean['League']:
    if balanceCount == clean_list[0]:
        count[0] = count[0] + 1
    elif balanceCount == clean_list[1]:
        count[1] = count[1] + 1
    elif balanceCount == clean_list[2]:
        count[2] = count[2] + 1
    elif balanceCount == clean_list[3]:
        count[3] = count[3] + 1
    elif balanceCount == clean_list[4]:
        count[4] = count[4] + 1
    elif balanceCount == clean_list[5]:
        count[5] = count[5] + 1
    elif balanceCount == clean_list[6]:
        count[6] = count[6] + 1
    elif balanceCount == clean_list[7]:
        count[7] = count[7] + 1
    elif balanceCount == clean_list[3]:
        count[7] = count[7] + 1

print(count)

[4553, 6010, 4716, 5554, 5253, 5477, 3336, 4266]

In [37]:
print(clean_list)

['championship' 'premier-league' 'bundesliga' 'laliga' 'ligue-1' 'serie-a'
 'serie-b' 'league-one']

In [38]:
minuteByMinute

,Unnamed: 0,ID,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
0,28,28,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Home,-,-
1,29,29,-,-,-,-,-,-,-,-,...,-,-,Yellow_Home,-,-,-,Goal_Home,Yellow_Home,-,-
2,30,30,-,-,-,-,Goal_Away,-,-,-,...,-,-,-,-,-,-,Yellow_Away,-,-,"Yellow_Away,Yellow_Home"
3,31,31,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,Yellow_Away
4,32,32,-,-,Goal_Home,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,"Yellow_Away,Red_Card_Home"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34737,52965,52965,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
34738,52968,52968,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34739,52969,52969,-,-,-,-,Goal_Away,-,Yellow_Away,-,...,-,-,-,-,-,-,-,-,-,-
34740,52971,52971,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34741,52972,52972,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,Yellow_Away,-,-,-