In [274]:
# Classic Imports
import pandas as pd
import re
import copy

In [275]:
# Getting all the Datasets
semiClean = pd.read_csv('CSV\semi_clean_one.csv')
minuteByMinute = pd.read_csv('CSV\MinuteByMinute.csv', dtype='object')
rawInc = pd.read_csv('CSV\RawINCData.csv')

In [276]:
semiClean = semiClean.dropna(subset = ['INC'])

In [277]:
clean_list = semiClean['League'].unique()
count = [0, 0, 0, 0, 0, 0 ,0 ,0]

for balanceCount in semiClean['League']:
    if balanceCount == clean_list[0]:
        count[0] = count[0] + 1
    elif balanceCount == clean_list[1]:
        count[1] = count[1] + 1
    elif balanceCount == clean_list[2]:
        count[2] = count[2] + 1
    elif balanceCount == clean_list[3]:
        count[3] = count[3] + 1
    elif balanceCount == clean_list[4]:
        count[4] = count[4] + 1
    elif balanceCount == clean_list[5]:
        count[5] = count[5] + 1
    elif balanceCount == clean_list[6]:
        count[6] = count[6] + 1
    elif balanceCount == clean_list[7]:
        count[7] = count[7] + 1
    elif balanceCount == clean_list[3]:
        count[7] = count[7] + 1

print(count)

[4553, 6010, 4716, 5554, 5253, 5477, 3336, 4266]

In [278]:
print(clean_list)

['championship' 'premier-league' 'bundesliga' 'laliga' 'ligue-1' 'serie-a'
 'serie-b' 'league-one']

In [279]:
minuteByMinute

,Unnamed: 0,ID,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
0,28,28,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Home,-,-
1,29,29,-,-,-,-,-,-,-,-,...,-,-,Yellow_Home,-,-,-,Goal_Home,Yellow_Home,-,-
2,30,30,-,-,-,-,Goal_Away,-,-,-,...,-,-,-,-,-,-,Yellow_Away,-,-,"Yellow_Away,Yellow_Home"
3,31,31,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,Yellow_Away
4,32,32,-,-,Goal_Home,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,"Yellow_Away,Red_Card_Home"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34737,52965,52965,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
34738,52968,52968,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34739,52969,52969,-,-,-,-,Goal_Away,-,Yellow_Away,-,...,-,-,-,-,-,-,-,-,-,-
34740,52971,52971,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34741,52972,52972,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,Yellow_Away,-,-,-

In [280]:
redCardOnly = rawInc.copy()
drop_red_list = []

count_red_home = 0
for red_card_home in redCardOnly['Red_Card_Home']:
    if red_card_home > 0:
        drop_red_list.append(count_red_home)
    count_red_home = count_red_home + 1
    
count_red_away = 0
for red_card_away in redCardOnly['Red_Card_Away']:
    if red_card_away > 0 and count_red_away not in drop_red_list:
        drop_red_list.append(count_red_away)
    count_red_away = count_red_away + 1

In [281]:
def rangeTwo(x, y):
    Final = []
    while x < y:
        Final.append(x)
        x = x + 1
    return Final
    
redCardData = minuteByMinute.copy()
maxRange = int(len(redCardData))
actual_drop_list = []

for drop_row in rangeTwo(0, maxRange):
    if drop_row not in drop_red_list:
        actual_drop_list.append(drop_row)

redCardData = redCardData.drop(actual_drop_list)
redCardOnly = redCardOnly.drop(actual_drop_list)

In [282]:
redCardData

,Unnamed: 0,ID,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
4,32,32,-,-,Goal_Home,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,"Yellow_Away,Red_Card_Home"
13,42,42,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,-,-,-
16,45,45,-,-,-,-,-,-,-,-,...,-,-,-,-,-,Goal_Home,-,-,-,-
26,55,55,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,57,57,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34667,52803,52803,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Goal_Home,-,-
34668,52804,52804,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34703,52875,52875,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,-,-,-,-
34704,52876,52876,-,-,-,-,-,-,-,-,...,Goal_Home,-,-,-,-,-,-,-,-,-
34709,52889,52889,-,-,-,Yellow_Away,-,-,-,-,...,-,-,-,-,-,-,Goal_Home,-,-,-

In [283]:
primary_red_list = []
for check_red in redCardData.index:
    secondary_red_list = []
    count = 0
    for minute_count in redCardData.loc[check_red]:
        minute_count_list = minute_count.split(',')
        for individual_action in minute_count_list:
            if individual_action == 'Red_Card_Home' or individual_action == 'Red_Card_Away':
                secondary_red_list.append(count - 2)
        count = count + 1
    primary_red_list.append(secondary_red_list)

In [284]:
count_unusable = 0
drop_unusable_data = []
for unusable_data in primary_red_list:
    if len(unusable_data) == 2:
        drop_unusable_data.append(count_unusable)
    count_unusable = count_unusable + 1

In [285]:
drop_index_list = []
for drop_unusable_real in drop_unusable_data:
    drop_index = int(redCardData.iloc[drop_unusable_real].name)
    drop_index_list.append(drop_index)
    
redCardData = redCardData.drop(drop_index_list)
redCardData

,Unnamed: 0,ID,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
4,32,32,-,-,Goal_Home,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,"Yellow_Away,Red_Card_Home"
13,42,42,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,-,-,-
26,55,55,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,57,57,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
29,58,58,-,-,-,-,-,-,-,Goal_Home,...,-,Yellow_Home,-,Goal_Home,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34667,52803,52803,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Goal_Home,-,-
34668,52804,52804,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34703,52875,52875,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,-,-,-,-
34704,52876,52876,-,-,-,-,-,-,-,-,...,Goal_Home,-,-,-,-,-,-,-,-,-
34709,52889,52889,-,-,-,Yellow_Away,-,-,-,-,...,-,-,-,-,-,-,Goal_Home,-,-,-

In [286]:
primary_double_list = []
for check_double in redCardData.index:
    checker_for_double = False
    for double_count in redCardData.loc[check_double]:
        double_count_list = double_count.split(',')
        if len(double_count_list) > 1:
            checker_for_double = True
    if checker_for_double == True:
        primary_double_list.append(check_double)

In [287]:
redCardData = redCardData.drop(primary_double_list)

In [288]:
double_red_list = []
for last_drop in redCardData.index:
    red_one_check = 0
    for last_red_check in redCardData.loc[last_drop]:
        if last_red_check == 'Red_Card_Home' or last_red_check == 'Red_Card_Away':
            red_one_check = red_one_check + 1
    if red_one_check > 1:
        double_red_list.append(last_drop)

In [289]:
redCardData = redCardData.drop(double_red_list)

In [290]:
redCardData

,Unnamed: 0,ID,M0,M1,M2,M3,M4,M5,M6,M7,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,42,42,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,-,-,-
26,55,55,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,57,57,-,-,-,-,-,-,Goal_Home,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
29,58,58,-,-,-,-,-,-,-,Goal_Home,...,-,Yellow_Home,-,Goal_Home,-,-,-,-,-,-
33,62,62,-,-,-,-,-,-,-,-,...,-,-,-,Goal_Home,-,-,-,-,-,Yellow_Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,52770,52770,-,Yellow_Away,-,-,Goal_Away,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34667,52803,52803,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Goal_Home,-,-
34668,52804,52804,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34703,52875,52875,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,-,-,-,-
34709,52889,52889,-,-,-,Yellow_Away,-,-,-,-,...,-,-,-,-,-,-,Goal_Home,-,-,-

In [291]:
# Nothing = 0
# Goal Home = 1
# Yellow Home = 2
# Red Card Home = 3
# Own Home = 4
# Goal Away = -1
# Yellow Away = -2
# Red Card Away = -3
# Own Away = -4
# 3.566 x 70% = 2.489 / 1.067

beforeRedCard = redCardData.copy()
afterRedCard = redCardData.copy()

beforeRedCard = beforeRedCard.drop(['Unnamed: 0', 'ID'], axis=1)
afterRedCard = afterRedCard.drop(['Unnamed: 0', 'ID'], axis=1)

In [292]:
beforeRedCard

,M0,M1,M2,M3,M4,M5,M6,M7,M8,M9,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,-,-,-,-,-,-,Goal_Home,-,-,-,...,-,-,-,-,-,-,-,-,-,-
26,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,-,-,-,-,-,-,Goal_Home,-,-,-,...,-,-,-,-,-,-,-,Yellow_Away,-,-
29,-,-,-,-,-,-,-,Goal_Home,-,-,...,-,Yellow_Home,-,Goal_Home,-,-,-,-,-,-
33,-,-,-,-,-,-,-,-,-,-,...,-,-,-,Goal_Home,-,-,-,-,-,Yellow_Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,-,Yellow_Away,-,-,Goal_Away,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34667,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,Goal_Home,-,-
34668,-,-,-,-,-,-,-,-,-,Goal_Home,...,-,-,-,-,-,-,-,-,-,-
34703,-,-,-,-,-,-,-,-,-,-,...,-,-,-,Yellow_Home,-,-,-,-,-,-
34709,-,-,-,Yellow_Away,-,-,-,-,-,-,...,-,-,-,-,-,-,Goal_Home,-,-,-

In [293]:
for transform in beforeRedCard.index:
    for transform_column in rangeTwo(0, len(beforeRedCard.columns)):
        name_column = 'M' + str(transform_column)
        if beforeRedCard.loc[transform, name_column] == '-':
            beforeRedCard.loc[transform, name_column] = 0
        elif beforeRedCard.loc[transform, name_column] == 'Goal_Home':
            beforeRedCard.loc[transform, name_column] = 1
        elif beforeRedCard.loc[transform, name_column] == 'Yellow_Home':
            beforeRedCard.loc[transform, name_column] = 2
        elif beforeRedCard.loc[transform, name_column] == 'Red_Card_Home':
            beforeRedCard.loc[transform, name_column] = 3
        elif beforeRedCard.loc[transform, name_column] == 'Own_Home':
            beforeRedCard.loc[transform, name_column] = 4
        elif beforeRedCard.loc[transform, name_column] == 'Goal_Away':
            beforeRedCard.loc[transform, name_column] = -1
        elif beforeRedCard.loc[transform, name_column] == 'Yellow_Away':
            beforeRedCard.loc[transform, name_column] = -2
        elif beforeRedCard.loc[transform, name_column] == 'Red_Card_Away':
            beforeRedCard.loc[transform, name_column] = -3
        elif beforeRedCard.loc[transform, name_column] == 'Own_Away':
            beforeRedCard.loc[transform, name_column] = -4

beforeRedCard

,M0,M1,M2,M3,M4,M5,M6,M7,M8,M9,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,-2,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,2,0,1,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,0,-2,0,0,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
34668,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34703,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
34709,0,0,0,-2,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [294]:
for remove_after in beforeRedCard.index:
    red_detect = False
    for column_after in rangeTwo(0, len(beforeRedCard.columns)):
        name_before = 'M' + str(column_after)
        if beforeRedCard.loc[remove_after, name_before] == 3 or beforeRedCard.loc[remove_after, name_before] == -3:
            red_detect = True
        elif red_detect == True:
            beforeRedCard.loc[remove_after, name_before] = 0

beforeRedCard

,M0,M1,M2,M3,M4,M5,M6,M7,M8,M9,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,0,-2,0,0,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34668,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34703,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34709,0,0,0,-2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [297]:
for transform_after in afterRedCard.index:
    for transform_column_after in rangeTwo(0, len(afterRedCard.columns)):
        name_column_after = 'M' + str(transform_column_after)
        if afterRedCard.loc[transform_after, name_column_after] == '-':
            afterRedCard.loc[transform_after, name_column_after] = 0
        elif afterRedCard.loc[transform_after, name_column_after] == 'Goal_Home':
            afterRedCard.loc[transform_after, name_column_after] = 1
        elif afterRedCard.loc[transform_after, name_column_after] == 'Yellow_Home':
            afterRedCard.loc[transform_after, name_column_after] = 2
        elif afterRedCard.loc[transform_after, name_column_after] == 'Red_Card_Home':
            afterRedCard.loc[transform_after, name_column_after] = 3
        elif afterRedCard.loc[transform_after, name_column_after] == 'Own_Home':
            afterRedCard.loc[transform_after, name_column_after] = 4
        elif afterRedCard.loc[transform_after, name_column_after] == 'Goal_Away':
            afterRedCard.loc[transform_after, name_column_after] = -1
        elif afterRedCard.loc[transform_after, name_column_after] == 'Yellow_Away':
            afterRedCard.loc[transform_after, name_column_after] = -2
        elif afterRedCard.loc[transform_after, name_column_after] == 'Red_Card_Away':
            afterRedCard.loc[transform_after, name_column_after] = -3
        elif afterRedCard.loc[transform_after, name_column_after] == 'Own_Away':
            afterRedCard.loc[transform_after, name_column_after] = -4

afterRedCard

,M0,M1,M2,M3,M4,M5,M6,M7,M8,M9,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,-2,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,2,0,1,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,0,-2,0,0,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
34668,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34703,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
34709,0,0,0,-2,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [308]:
def rangeReverse(x, y):
    Final = []
    while y > x:
        y = y - 1
        Final.append(y)
    return Final

for remove_before in afterRedCard.index:
    red_detect_before = False
    for column_before in rangeReverse(0, len(afterRedCard.columns)):
        name_after = 'M' + str(column_before)
        if afterRedCard.loc[remove_before, name_after] == 3 or afterRedCard.loc[remove_before, name_after] == -3:
            red_detect_before = True
        elif red_detect_before == True:
            afterRedCard.loc[remove_before, name_after] = 0

afterRedCard

,M0,M1,M2,M3,M4,M5,M6,M7,M8,M9,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,-2,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,2,0,1,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34653,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
34668,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34703,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
34709,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0